# we'll use alpine here because it's smalle but we want the node base
# FROM node:14-alpine
# WORKDIR /app
# CMD ["node", ""]

# FROM node:14-alpine
# WORKDIR /app
# ENTRYPOINT ["npm"]

FROM bash
ENTRYPOINT ["ls"]